### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ved-un** [zakariaGatter/xbps-hist#1]
```
[void@void ~/.local/bin]$ LC_ALL=C xbps-hist -l
mktemp: invalid template, '/tmp/xbps-hist.XXXXXX', contains directory separator
touch: cannot touch '': No such file or directory
/home/void/.local/bin/xbps-hist: line 34: : No such file or directory
/home/void/.local/bin/xbps-hist: line 34: : No such file or directory
/home/void/.local/bin/xbps-hist: line 93: : No such file or directory
[void@void ~/.local/bin]$
```

**Comment by zakariaGatter** [comment]
im sorry sorry this error and thank you for report it 

this is the fix 

you need to modify xbps-hist file and change `mktemp -q -t /tmp/$name.XXXXXX` TO `mktemp -qu /tmp/$name.XXX`

and im gonna correct this issue now 

thank you again

**Comment by Ved-un** [comment]
Happy to help...
and also correct the address in the README 
_git clone https://gitlab.com/zakariaGatter/xbps-hist.git ~/xbps-hist_  on the _https://github.com_

**Comment by zakariaGatter** [comment]
yes thank you
