### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Ved-un** [zakariaGatter/xbps-hist#2]
Hello.
I like your script, but could you tell me how to change your script so that instead of this output : 
`2022-03-31 07:41:51 Installed   base-system                       successfully   (rootdir: /).`

there was output with the version number and without the unnecessary "successfully (rootdir: /)."
`2022-03-31 07:41:51 Installed   base-system-0.114_1`

**Comment by zakariaGatter** [comment]
thank you for using xbps-hist 
for your request you need to change :

FROM
```bash
pkg_name=${line[7]%-*}
pkg_name=${pkg_name:1}
```

TO 
```bash
pkg_name=${line[7]:1:-1}
```


and you need to change all the lines : 

FROM
```bash
$date_time ${line[6]}, $pkg_name, ${line[8]}, ${line[9]} ${line[10]}
```

TO
```bash
$date_time ${line[6]}, $pkg_name
```

before you go star this repo ⭐  

i hope you like my project

**Comment by Ved-un** [comment]
Wow, thank you so much!

And how can you make the output the color of the words - Installed Removed Updated?
how it's done in **paclog** (Arch) - https://github.com/xfgusta/paclog

![img-01](https://user-images.githubusercontent.com/48730277/161197692-eb1ebf2f-3e2d-4c4d-95b7-73f5988df5f7.png)

**Comment by zakariaGatter** [comment]
its look beautiful but ill work on it another time

**Comment by Ved-un** [comment]
Thanks.
It's not about beauty, it's just so convenient to track changes.

**Comment by zakariaGatter** [comment]
Thanks to your feedback im thinking of adding options for short and long listing form
