### ISSUE TITLE
Possible Capitalization issue with group name

### ISSUE THREAD

**Issue by juneflowers** [zakariaGatter/xbps-hist#3]
Hey this could possibly be user error but just incase it isn't I figured i'd check. I'm trying to add my user to the "Socklog" group however I'm told it's an invalid name because the "socklog" group already exists. So I add myself to "socklog" successfully and then upon running xbps-hist I get an error saying I'm not in the Socklog group. Notice the capital S.

(Services are enabled)

![image](https://user-images.githubusercontent.com/63337938/182292319-26d23161-61e9-4fec-9cfd-5e508ded82e4.png)

**Comment by zakariaGatter** [comment]
Fisrt of all thank you so mcuh for using __xbps-hist__ i jope it will help you 

I think i fixed the issue with this [commit](https://github.com/zakariaGatter/xbps-hist/commit/126dcee249f4c832e4c3e80401c3a95fec3f5a1a) Please run `git pull` on __xbps-hist__ repository and try again

**Comment by juneflowers** [comment]
No thank you! Very useful tool that I'll be using and keeping an eye on. I should note one other thing, if you run it with no flags it outputs nothing at all which could lead some people to think it's not working.
![image](https://user-images.githubusercontent.com/63337938/182419328-07bf7717-06eb-4c5b-837a-a393cfd30feb.png)

But it's working for me now! Appreciate the quick fix.
