### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Ved-un** [zakariaGatter/xbps-hist#4]
Hello. Please tell me why it doesn't work for me?

![2022-08-20_08-11](https://user-images.githubusercontent.com/48730277/185730048-4ed162e1-b4d1-4a90-bde6-5c5427694175.png)

**Comment by zakariaGatter** [comment]
Can u run the groups command and show me the resoult

**Comment by Ved-un** [comment]
```
[void@void ~]$ groups
void wheel floppy audio video cdrom optical storage kvm xbuilder socklog
```

**Comment by Ved-un** [comment]
Sorry, everything is working now.
Apparently it was necessary to reboot the system.

Thank you, the issue can be closed.
